language: java

dist: trusty

jdk:
    - openjdk17

sudo: true

before_install:
    - chmod +x mvnw

script:
    - chmod +x ./.ci/unit-test.sh
    - chmod +x ./.ci/integration-test.sh
    - ./.ci/integration-tests.sh
    - ./.ci/unit-tests.sh

codecov:
    token: 66c93800-0c25-48c6-95c0-fea82cd5dd4

after_success:
    - bash <(curl -s https://codecov.io/bash)