version: "3"
services:
    h2:
        container_name: 'h2'
        hostname: 'h2'
        image: oscarfonts/h2
        ports:
            - "8181:8181"
            - "1521:1521"
    transaction:
        image: muriloalvesdev/transaction
        network_mode: bridge
        container_name: transaction
        expose:
            - 8080
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - h2